### ISSUE TITLE
when showing a list of variants with problems do not show variants without valid evidence items

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-api-client#19]
Hi @LeiChen0218.  Can we change the behavior of `civic-api-client variants-list` so that it will not report a variant unless it has at least one accepted evidence item?

**Comment by LeiChen0218** [comment]
Sure. I'll work on it soon.

Sent from my iPhone

On Mar 11, 2016, at 17:08, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @LeiChen0218https://github.com/LeiChen0218. Can we change the behavior of civic-api-client variants-list so that it will not report a variant unless it has at least one accepted evidence item?

##
